=== Artalz/Vezba4/magacin.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
            targetNamespace=" http://www.mytestschema.rs "
            xmlns="http://www.mytestschema.rs"
            elementFormDefault="qualified">

    <xs:element name="Magacin">
        <xs:complexType>
            <xs:sequence minOccurs="1" maxOccurs="unbounded">
                <xs:element ref="Artikal"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Artikal">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Naziv"/>
                <xs:element ref="DatumIzrade"/>
                <xs:element ref="Cena"/>
                <xs:element ref="Kompanija"/>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="Email"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Naziv">
        <xs:complexType>
            <xs:attribute name="sifra" use="required">
                <xs:simpleType>
                    <xs:restricion base="xs:string">
                        <xs:minLength value="3"/>
                        <xs:maxLength value="30"/>
                    </xs:restricion>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>

    <xs:element name="DatumIzrade">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Dan"/>
                <xs:element ref="Mesec"/>
                <xs:element ref="Godina"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Dan">
        <xs:simpleType>
            <xs:restricion base="xs:string">
                <xs:pattern value="[1-9]|[1-2][0-9]|3[0-1]"/>
            </xs:restricion>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Mesec">
        <xs:simpleType>
            <xs:restricion base="xs:string">
                <xs:pattern value="[1-9]|1[0-2]"/>
            </xs:restricion>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Cena">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="nonNegativeInteger">
                    <xs:attribute default="din" name="valuta">
                        <xs:simpleType>
                            <xs:restricion base="xs:NMTOKEN">
                                <xs:enumeration value="din"/>
                                <xs:enumeration value="eur"/>
                            </xs:restricion>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="nonNegativeInteger">
        <xs:restricion base="xs:integer">
            <xs:minInclusive value="0"/>
        </xs:restricion>
    </xs:simpleType>

    <xs:element name="Kompanija">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Ime"/>
                <xs:element minOccurs="1" maxOccurs="unbounded" ref="Adresa"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Ime" type="xs:string"/>
    <xs:element name="Adresa" type="xs:string"/>

    <xs:element name="Email">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="emailRestrikcija">
                    <xs:attribute use="required" name="tip">
                        <xs:simpleType>
                            <xs:restricion base="xs:NMTOKEN">
                                <xs:enumeration value="privatni"/>
                                <xs:enumeration value="sluzbeni"/>
                            </xs:restricion>
                        </xs:simpleType>
                    </xs:attribute>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="emailRestrikcija">
        <xs:restricion base="xs:string">
            <xs:pattern value="[a-zA-Z0-9]{5-20}@\c{4-8}.com"/>
        </xs:restricion>
    </xs:simpleType>


<xs:schema>

=== Artalz/Vezba4/magacin.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Magacin SYSTEM "magacin.dtd">
<Magacin xmlns="http://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3schools.com magacin.xsd">


    <Artikal>
        <Naziv sifra="1">Jogurt</Naziv>
        <DatumIzrade>
            <Dan>5</Dan>
            <Mesec>7</Mesec>
            <Godina>2020</Godina>
        </DatumIzrade>
        <Cena valuta="din">din</Cena>
        <Kompanija>
            <Ime>Imlek</Ime>
            <Adresa>Beograd</Adresa>
        </Kompanija>
        <Email tip="privatni">em@ma.com</Email>
    </Artikal>

    <Artikal>
        <Naziv sifra="1">Jogurt</Naziv>
        <DatumIzrade>
            <Dan>5</Dan>
            <Mesec>7</Mesec>
            <Godina>2020</Godina>
        </DatumIzrade>
        <Cena valuta="din">din</Cena>
        <Kompanija>
            <Ime>Imlek</Ime>
            <Adresa>Beograd</Adresa>
        </Kompanija>
        <Email tip="privatni">em@ma.com</Email>
    </Artikal>

</Magacin>
